### PR TITLE
fix: 🐛 use api paging information to loop attractions

### LINKED ISSUE #46: Attractions/thingsToDo dont work
https://my.apify.com/view/runs/Ty8iHOGDZqREnrFyD
For some reason it works for Roudnice - https://my.apify.com/view/runs/RDXLjblSBy4lTHiCQ ?

### PR DESCRIPTION
**Pull request by gustavotr**
✅ Closes: #46

### CODE REVIEW

File: src/tools/attraction-tools.js [hunk 1]
```diff
@@ -12,19 +12,32 @@ const { findLastReviewIndex } = require('./general');
...
-        if (data.length < limit || checkMaxItemsLimit(data.length)) break;
+        await Promise.all(data.map((attraction) => attractionsStore.setValue(`${attraction.location_id}`, attraction)));
+        if (!next || attractionsCount >= Number(totalResults) || checkMaxItemsLimit(attractionsCount)) {
+            hasReachedLimit = true;
+        }
     }
+
+    /** @type {any[]} */
+    const attractions = [];
+    await attractionsStore.forEachKey(async (key) => attractions.push(await attractionsStore.getValue(key)));
```
Comment (metalwarrior665) [inline src/tools/attraction-tools.js]: As with the other PR, please not use the KV like this and instead use the state approach.

**Review by metalwarrior665 — CHANGES_REQUESTED** [review]

**Review by metalwarrior665 — APPROVED** [review]
I didn't test it do @zpelechova please test after merge
